import gzip

def search(term):
    print(f"--- Search: {term} ---")
    with open('yarn.tiny', 'r', encoding='utf-8') as f:
        for line in f:
            if term in line:
                print(line.strip())

search('MinecraftClient\t')
search('MinecraftClient\tgetInstance')
search('MinecraftClient\tplayer')
search('MinecraftClient\tworld')
search('MinecraftClient\tgameRenderer')
search('MinecraftClient\toptions')
search('MinecraftClient\tmouse')
search('Mouse\tlockCursor')
search('Mouse\tunlockCursor')
search('Entity\tgetX')
search('Entity\tgetY\t')
search('Entity\tgetZ')
search('Entity\tgetBoundingBox')
search('Entity\tgetVelocity')
search('Entity\tsetVelocity')
search('Entity\tgetYaw')
search('Entity\tgetPitch')
search('Entity\tsetYaw')
search('Entity\tsetPitch')
search('Entity\tgetName')
search('LivingEntity\tgetHealth')
search('LivingEntity\tgetMaxHealth')
search('Camera\tgetPos')
search('Camera\tgetPitch')
search('Camera\tgetYaw')
search('GameRenderer\tgetCamera')
search('GameRenderer\tgetFov')
search('Options\tfov')
search('World\tgetPlayers')
search('ClientPacketListener\t')
search('ClientPlayNetworkHandler\t')
search('MinecraftClient\tgetNetworkHandler')
search('ClientPlayNetworkHandler\tsendPacket')
search('PlayerMoveC2SPacket$PositionAndOnGround\t<init>')
search('PlayerInteractEntityC2SPacket\tattack')
search('MinecraftClient\tcrosshairTarget')
search('HitResult\tgetType')
search('EntityHitResult\tgetEntity')
search('PlayerEntity\tattack')
search('PlayerEntity\tswingHand')
